#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Hermternal — code signing and notarization setup"

# This wizard is interactive: every stage reads a pasted value. Without a TTY
# `read` returns empty immediately and each stage fails for the wrong reason,
# so require one up front. `ssh host 'cmd'` has no TTY; `ssh -t` and
# Terminal.app on the Mac both do.
if [[ ! -t 0 ]]; then
  warn "No terminal attached, so nothing you paste can be read."
  say "Run this from Terminal.app on the Mac, or over 'ssh -t'."
  exit 1
fi

# Keychain lock state is per-user, not per-session, so an unlocked login
# keychain is reachable even over ssh. A locked one cannot be unlocked from a
# remote shell, because the Security framework has nowhere to draw the prompt.
if security show-keychain-info ~/Library/Keychains/login.keychain-db 2>&1 |
   grep -q "User interaction is not allowed"; then
  warn "The login keychain is locked and cannot be unlocked from here."
  say "Unlock it on the Mac (log in, or open Keychain Access) and re-run."
  exit 1
fi

# ── 1. Team ID ────────────────────────────────────────────────────────────
stage "Apple Developer — Team ID"
say "Notarization is tied to your developer team, so we need its ID."
open_url "https://developer.apple.com/account"
step "Sign in if prompted."
step "In the sidebar, open 'Membership details'."
step "Copy the 'Team ID' — 10 characters, letters and digits."
ask APPLE_TEAM_ID "Paste your Team ID:"
[[ -n "$APPLE_TEAM_ID" ]] || { warn "Team ID is required."; exit 1; }
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"

# ── 2. Developer ID Application certificate ───────────────────────────────
stage "Certificate — Developer ID Application"
say "Apple only notarizes builds signed with a 'Developer ID Application'"
say "certificate. Xcode can create the key, the request, and install the"
say "result in one pass, which avoids hand-making a CSR in Keychain Access."
note "Requires the Account Holder or Admin role on the team."
step "Open Xcode."
step "Xcode ▸ Settings ▸ Accounts."
step "Add your Apple ID with '+' if it is not listed, then select it."
step "Click 'Manage Certificates…' (bottom right)."
step "Click '+' ▸ 'Developer ID Application'."
step "Wait for it to appear in the list, then close the dialogs."
pause "Press Enter once the certificate is created."

# ── 3. Verify the identity landed in the keychain ─────────────────────────
stage "Verify — signing identity"
say "Checking the keychain for a usable Developer ID identity."
if ! security unlock-keychain -u ~/Library/Keychains/login.keychain-db 2>/dev/null; then
  warn "Could not unlock the login keychain automatically."
  say "Unlock it now (Keychain Access, or: security unlock-keychain)."
  pause "Press Enter once unlocked."
fi
IDENTITIES="$(security find-identity -v -p codesigning 2>/dev/null || true)"
printf '%s\n' "$IDENTITIES" | sed 's/^/    /'
CODESIGN_IDENTITY="$(
  printf '%s\n' "$IDENTITIES" |
    sed -n 's/.*"\(Developer ID Application[^"]*\)".*/\1/p' | head -1
)"
if [[ -z "$CODESIGN_IDENTITY" ]]; then
  warn "No 'Developer ID Application' identity found."
  say "Go back to stage 2 — a 'Mac Development' or 'Apple Development'"
  say "certificate will not work for notarized distribution."
  exit 1
fi
say "Found: $CODESIGN_IDENTITY"
write_env CODESIGN_IDENTITY "$CODESIGN_IDENTITY"

# ── 4. App Store Connect API key ──────────────────────────────────────────
stage "Notary credentials — App Store Connect API key"
say "notarytool needs credentials. An API key is preferred over an"
say "app-specific password: it does not expire when you change your Apple ID"
say "password, and it carries no access to the rest of your account."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Open the 'Keys' tab (Integrations ▸ App Store Connect API)."
step "Note the 'Issuer ID' shown above the table — it is a UUID."
ask ASC_ISSUER_ID "Paste the Issuer ID:"
step "Click '+' to generate a key. Name it 'hermternal-notary'."
step "Set Access to 'Developer', then Generate."
step "Copy the 'KEY ID' from the new row."
ask ASC_KEY_ID "Paste the Key ID:"
step "Click 'Download' on that row to get AuthKey_<KEYID>.p8."
note "Apple allows this download exactly once — keep the file."
say "Move it somewhere permanent, e.g. ~/.appstoreconnect/private_keys/"
ask ASC_KEY_PATH "Full path to the downloaded .p8 file:"
ASC_KEY_PATH="${ASC_KEY_PATH/#\~/$HOME}"
[[ -f "$ASC_KEY_PATH" ]] || { warn "No file at: $ASC_KEY_PATH"; exit 1; }
write_env ASC_ISSUER_ID "$ASC_ISSUER_ID"
write_env ASC_KEY_ID "$ASC_KEY_ID"
write_env ASC_KEY_PATH "$ASC_KEY_PATH"

# ── 5. Store the profile in the keychain ──────────────────────────────────
stage "Store the notarytool profile"
say "Saving the credentials under the profile name 'hermternal', so the"
say "release script never handles the key material itself."
if xcrun notarytool store-credentials hermternal \
     --key "$ASC_KEY_PATH" \
     --key-id "$ASC_KEY_ID" \
     --issuer "$ASC_ISSUER_ID"; then
  say "Profile stored."
else
  warn "store-credentials failed — check the Issuer ID, Key ID, and .p8 path."
  exit 1
fi

# ── 6. Confirm Apple accepts the credentials ──────────────────────────────
stage "Verify — talk to the notary service"
say "Asking Apple for this account's submission history. An empty list is a"
say "pass: it proves the credentials authenticate."
if xcrun notarytool history --keychain-profile hermternal | head -20; then
  say "Credentials work."
else
  warn "Apple rejected the credentials."
  exit 1
fi
say ""
say "Next: bash Scripts/release.sh"

finish
